### ISSUE TITLE
Text not getting highlighted when selecting

### ISSUE THREAD

**Issue by zjays** [zotero/zotero-word-for-windows-integration#11]
I'm on Windows 10 and Word 2013, and I'm having a problem using Zotero.dotm from ac9c63ade827c66fe805c6d4bdffd3408c3ef002. When this is placed in my startup folder, I have issues with text not getting highlighted or "painted over" when I select text using a mouse button hold and drag. The problem is quite similar to the issue posted here: http://answers.microsoft.com/en-us/office/forum/office_2013_release-word/i-cant-use-my-mouse-to-paint-over-text-in-word/c45354e2-b43a-4900-9c79-0e3b012a345b

The problem goes away when I use an earlier version of Zotero.dotm posted on April 28 2014 here: https://github.com/zotero/zotero-word-for-windows-integration/issues/1#issuecomment-41556418

**Comment by bwiernik** [comment]
It appears to be an issue with the UpdateRibbon function. 
https://forums.zotero.org/discussion/51839/word-for-windows-plugin-text-selections-display-incorrectly/#Item_1


Interestingly, if I put both the official dotm and the original dotm from the pull request in the Word Startup folder, text highlighting works correctly.
