### ISSUE TITLE
Zotero causes mouse pointer to twitch when moving cursor

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-word-for-windows-integration#12]
I can't really capture it in a screencast, but the pointer goes into thinking mode for a moment.

I'm guessing this is the result of dynamic Zotero buttons that change from Add Citation to Edit Citation if the cursor is positioned inside a Zotero field code. It is most noticeable when pressing and holding the keyboard arrow keys to move the cursor. Best I can tell this is more annoying than anything, but it might cause measurable slowdowns on slower machines (I couldn't measure the difference).

If we can't figure out how to fix the twitch, we could leave the button static and call it Add/Edit Citation.

**Comment by bwiernik** [comment]
It appears that the dynamic button is causing slowdowns on some users' machines:
https://forums.zotero.org/discussion/52528/new-zotero-word-addin-causing-spinning-blue-wheel-in-ms-word/#Item_0
