### ISSUE TITLE
Zotero does not add itself to the list of tabs under Customize Ribbon

### ISSUE THREAD

**Issue by aurimasv** [zotero/zotero-word-for-windows-integration#15]
This is under Word Options -> Customize Ribbon (the list on the right)

Not a big deal, but EndNote and ColWiz both do. Mendeley does not, but probably only because we do not.

**Comment by bwiernik** [comment]
I looked into this a bit. It seems that we would need to build an add-in .dll with appropriate preferences, rather than simply using the template.

**Comment by bwiernik** [comment]
(i.e., a full-fledged COM add-in)

**Comment by aurimasv** [comment]
How did you design the tab (i.e. what tools did you use, if any)? Did you edit the customUI.xml directly and then re-packed the template?

**Comment by simonster** [comment]
That's what I did. Not sure if @marckl67 had a different approach.

**Comment by bwiernik** [comment]
Word 2016 on Mac and Windows has started to show the Zotero tab in the customize toolbar/QAT dialog in a recent update.

**Comment by adomasven** [comment]
Closing as Office 2016 and #28 essentially solve this and there won't be any efforts to support earlier versions of Office.
