### ISSUE TITLE
Office 2016: New dark and colorful themes need light colored icons

### ISSUE THREAD

**Issue by bwiernik** [zotero/zotero-word-for-windows-integration#16]
Office 2016 added Dark Gray and Colorful (Blue) themes that change the color of the ribbon tab labels and the quick access toolbar. The Colorful theme is the default. All of the built-in icons that are pinned to the Quick Access Toolbar change color to white outlines when using these new themes (but keep the standard full-color icons for the old White theme). All of Zotero's custom icons are hard to see when using the Colorful (default) or Dark Gray themes. The Add Citation, Edit Citation, and Document Preferences icons also look fairly messy when pinned there as well. 

The add-in should include a set of icons designed for the Quick Access Toolbar. Given that the built-in icons change color schemes, presumably there must be a way to have Word automatically display the correct version of the icon or to test for which theme is being used.

**Comment by simonster** [comment]
As far as I know there is no mechanism for third-party developers to do this, but if you can figure out a way then we can try.

**Comment by bwiernik** [comment]
It appears that Word has started to automatically create white line-art versions of third-party icons when added to the Quick Access Toolbar. However, the grey used in most of the icons for outlines, to represent "text", and as filler makes most of them (other than Refresh) look really bad. The Add/Edit Citation button also doesn't rescale well to a small icon when placed in the QAT or in other places in the Ribbon. 

I will look into whether a separate small Add/Edit icon can be included in the template and also try to find some time to design some higher-contrast icons that will switch better between the light and dark themes.

**Comment by adomasven** [comment]
Closed with #28.
