### ISSUE TITLE
Installation .dot vs .dotm not working

### ISSUE THREAD

**Issue by bwiernik** [zotero/zotero-word-for-windows-integration#17]
The installation choice (i.e., just .dot, just .dotm, or both) described in commit f822d2c7a481ff7b0fe9e9e83f50715291022839 is not working for me on Windows 10 Office 2013 or 2016. Both templates get installed when installing the add-in or choosing the reinstall button from Zotero.

**Comment by adomasven** [comment]
This works properly now for sure and also we've deprecated support for Word 2003 so .dot files are not really an issue (although related code should be cleaned up eventually).
