### ISSUE TITLE
Improving Quick Format Citation Dialog: add OK and Cancel icons

### ISSUE THREAD

**Issue by larmarange** [zotero/zotero-word-for-windows-integration#20]
Recently, I was teaching Zotero to my students, and most of them has issues with the _quick format citation dialog_. To validate, you need to press <kbd>Enter</kbd> and to cancel you need to press <kbd>Echap</kbd>.

Most of my students were searching a button / icon to validate with their mouse. Used to touch interface, the idea of using the keyboard to validate/cancel didn't came up.

Therefore, it could be appropriate to add to the citation dialog a validate icon (and a cancel icon) on the right of the form (like people are now used to in search forms on internet or smartphone) to allow validation/cancellation with a mouse.

Best regards

**Comment by adomasven** [comment]
Please post feature requests on [Zotero forums](https://forums.zotero.org/). This tracker is for developer use only.
