### ISSUE TITLE
Missing entry in references list

### ISSUE THREAD

**Issue by wbt** [zotero/zotero-word-for-windows-integration#22]
[In this example document,](https://github.com/zotero/zotero-word-for-windows-integration/files/366999/Missing-Zotero-reference.docx) there are two citations, but only one shows up in the reference list.  (This is the opposite problem of [having an extra](https://github.com/zotero/zotero/issues/1064).) 
When I toggle field codes, I can see that the second reference has lots of reference data but that the first one is just "{ ADDIN ZOTERO_TEMP }."  Yet when the field is viewed as normal text, or even when trying to copy the field text out, it's shown as "[Davies 2011]" though neither of those pieces of information appear to be in the field codes.

Why is whatever mechanism used to get that information for display in the inline citation unable to also add it to the references list?  Could we at least provide some way for the user to easily detect that there is an error where the inline citation will not have anything backing it up in the reference list? 

(If needed, the document style is "[ACM Transactions on Intelligent Systems and Technology](https://www.zotero.org/styles/transactions-on-intelligent-systems-and-technology)").

**Comment by adomasven** [comment]
Sorry this did not get addressed at the time of posting. This is a bug report that should have been pointed to be posted about on issue creation to [Zotero Forums](forums.zotero.org) where all such requests are handled and debugged with the user before it's deemed a word plugin problem.

We're not seeing reports of behavior described in the post so must have been some sort of one-off error.

**Comment by wbt** [comment]
The document is still there, as an example, and could still be investigated.

**Comment by adomasven** [comment]
If you're just seeing `{ ADDIN ZOTERO_TEMP }` for the field code of a citation it means that its insertion has gone wrong somehow. However, if you cannot reproduce the issue again, there is little we can do with an example document to debug it. Setting the field code to `{ ADDIN ZOTERO_TEMP }` is an intermediate step between citation insertion and final formatting and isn't unexpected in a document where setting the field code had failed for some reason.

**Comment by wbt** [comment]
How would the document know to put "[Davies 2011]" in the plaintext view when the field code is just `{ ADDIN ZOTERO_TEMP }`? With all the possible combinations of author names and years, I really don't think it's just a lucky coincidence to be getting that right.

**Comment by dstillman** [comment]
Obviously the plain-text citation comes from the data. Adomas's point is just that a field code of `{ ADDIN ZOTERO_TEMP }` in a document doesn't give us anything to go on to debug it. You'd have to be able to reproduce it.
