### ISSUE TITLE
Multiple bibliographies in one word document

### ISSUE THREAD

**Issue by robertour** [zotero/zotero-word-for-windows-integration#23]
This is a feature request to allow the creation of multiple bibliographies in one Word document. I suggest using of section breaks. At the interface levels, a thick box in the Add/Edit Bibliography that activates the use of sections should do it.

There is an old thread here discussing this possibility.
https://forums.zotero.org/discussion/28034/multiple-bibliographies-in-one-word-document/

**Comment by adomasven** [comment]
Please post feature requests on [Zotero forums](https://forums.zotero.org/). This feature is not being considered for the short-term and if it were, the issue should go in zotero/zotero.
