### ISSUE TITLE
Remove "Store references in document" checkbox

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#30]
This is obviously not a huge priority, but we should include references in documents without it being an option and not worry about it. I understand that this wasn't a feature in the beginning in Zotero, but I don't think there's any reason to worry about some extra filesize in 2017. People are (hopefully) not transferring their files in floppy disks anymore.

Is there any other reason I may have missed to have the option in there @simonster @adam3smith ?

**Comment by adam3smith** [comment]
I suppose you could use it as a check for which references are disconnected from Zotero (because those will throw an error without store references), but that seems like both an unlikely scenario and a clumsy solution. I think it's fine to just do this and not pref it. Mendeley, e.g., does that.
@rmzelle can you think of anything else?

**Comment by adomasven** [comment]
Yeah, just to clarify, I think we should store references (and yes it has benefits such as error checking and document-sharing/collaborating), but remove the checkbox/pref.

**Comment by zuphilip** [comment]
Should we care about documents written with Zotero versions before 3.0?

**Comment by rmzelle** [comment]
I think the current Document Preferences window shown when the user e.g. inserts their first reference is extremely wordy and intimidating, so I strongly support any reduction in text and toggles.

As far as I can tell, the only reason for the toggle is that embedded metadata would trip up Zotero versions before 3.0, which is no longer a relevant concern.

See https://www.zotero.org/support/3.0_changelog#changes_in_30b1_august_21_2011 ("Documents can now be shared with users of Zotero and other compatible software without using Zotero groups"). 3.0 went final in January 2012.

**Comment by rmzelle** [comment]
(the thing I would really appreciate in the Document Preferences is style previews)

**Comment by adomasven** [comment]
> I think the current Document Preferences window shown when the user e.g. inserts their first reference is extremely wordy and intimidating, so I strongly support any reduction in text and toggles.

Very true. Any other ideas for improvement?

**Comment by adam3smith** [comment]
If we keep this as a single tab (which I think we should) and keep the choice for Bookmarks (which also, I think we must), How about 

Fields (recommended)
Cannot be shared with LibreOffice. File must be saved as .doc/.docx

Bookmarks
Can be shared between Word and LibreOffice. Cannot be inserted in Footnotes.

**Comment by zuphilip** [comment]
> Any other ideas for improvement?

Sure :-) Actually, I would prefer to have an drop-down list for the citation style and possible the language in the ribbon itself. This would be same as Word references, Citavi or Mendeley are doing, e.g.

![](http://s3.amazonaws.com/libapps/accounts/26861/images/Insert_citation_styles.JPG)

On the other hand I would maybe move the "Remove field codes" into an advanced options dialog together with the option to choose between fields and bookmarks.

**Comment by rmzelle** [comment]
I think the current toggle between Fields and Bookmarks is overly complex. Users need to read all the text before they can make a decision. How about changing the current

![image](https://cloud.githubusercontent.com/assets/77951/23718339/1cd88732-0405-11e7-9f3b-cedf3e156bad.png)

to a single checkbox, "Enable LibreOffice compatibility", that's unchecked by default. You could add as explanation something like "With LibreOffice compatibility enabled, Zotero citations are inserted as bookmarks instead of Microsoft Word fields. Unlike fields, bookmarks are preserved across Word and LibreOffice in .doc(x) files. Bookmarks are more easily accidentally modified, and [cannot]/[should not] be inserted into footnotes or endnotes."

**Comment by adam3smith** [comment]
A checkbox, while simpler, suggests that you're adding compatibility rather than toggling between two options (one of them with significant downsides). I'm not sold on that.

**Comment by rmzelle** [comment]
Just renaming "Format Using:" to "Store Citations as:" would also already improve things. "Format" is rather ambiguous when we're talking about citations.

**Comment by rmzelle** [comment]
I also find "Automatically abbreviate journal titles" a misnomer for the option. Whether or not the style abbreviates journal titles is determined by the style. Instead, the toggle determines where the abbreviations come from. How about:

"Use automatically generated journal title abbreviations"
(If checked, MEDLINE journal title abbreviations are used that are based on the full titles stored in the "Publication" field. If unchecked, the value of the "Journal Abbr" field is used instead.)

**Comment by rmzelle** [comment]
I also find the Citation Style menu list rather claustrophobic. If it could be increased to e.g. 6 rows I'd be much happier.

**Comment by rmzelle** [comment]
> A checkbox, while simpler, suggests that you're adding compatibility rather than toggling between two options (one of them with significant downsides). I'm not sold on that.

I just rather see something that doesn't require the user to expend so much energy to understand what the choice means. If we can reduce it from the current 60+ words (which can generate loads of questions, like "What are fields?", "What are bookmarks?", "What are the differences between the two?", "Should I be worried about 'accidentally modifying' citations?") to 3 (where hopefully the majority of users think, "Oh, I don't care about LibreOffice compatibility, let's skip that"), that seems like a significant improvement.

**Comment by dstillman** [comment]
> I also find the Citation Style menu list rather claustrophobic. If it could be increased to e.g. 6 rows (up from the current 4)

We can increase it (after we pare down the rest of the dialog), but it's 5.5 lines for me on macOS.

**Comment by rmzelle** [comment]
> but it's 5.5 lines for me on macOS.

It looks like this for me on Windows 7:

![image](https://cloud.githubusercontent.com/assets/77951/23721674/a882d192-0410-11e7-87c6-0bd5c31182c6.png)

**Comment by adam3smith** [comment]
> I just rather see something that doesn't require the user to expend so much energy to understand what the choice means.

Full agreement there. That's why I suggested above to a) add "recommended" next to Fields to make clear that usually people should just run with that and otherwise pare down the words to <30.

**Comment by adam3smith** [comment]
btw. also agree with @zuphilip above. We get the question on how to change citation styles surprisingly often, so making that more accessible seems natural.

**Comment by bwiernik** [comment]
A dropdown menu to choose styles, ideally with a preview reference on mouseover, would be nice. I worry a bit about the length of the menu for users with many styles installed. Perhaps display the ten most recent styles with a More Styles option at the bottom?

Besides the style dropdown, I don't think any of the other items in the Preferences Pane particularly need to be very accessible. There could be an Advanced Preferences button that brings up the current pane to modify locale/abbreviation method/metadata storage, as well as the Remove Field Codes button. 

For the Fields/Bookmarks, how about:
> Store citation data using:
> Fields (recommended)
> Bookmarks (only for LibreOffice compatibility)

**Comment by KarlHegbloom** [comment]
I agree with removing the option regarding storing references in the document, and that those references should be stored in the document always. My [zotero-texmacs-integration](https://github.com/KarlHegbloom/zotero-texmacs-integration) needs those references present for some of it's features, and this way I don't have to worry about documenting that switch and telling users that they must enable that option to make it work right.

With regards to the style selection, and pop-up samples: The style editor shows samples or previews for the ones that are currently selected. What about with a new document, where none are selected yet? Should it pick one at random, or use the last one or two that the user had selected?

Also see: [propachi-texmacs](https://github.com/KarlHegbloom/propachi-texmacs) in bootstrap.js where I've monkey-patched some things inside of integration.js to make it work with my TeXmacs integration plugin. In particular, I've created an "affirmCitation" integration command, which is the same thing as "editCitation", only there is no dialog box---it just re-typesets the citation. I use this to retypeset after sub-cite cut and paste operations, etc.

I think that the maintainers of the Word and LibreOffice plugins might like to have a look a what I've done with that. Any ideas? (Sorry, this isn't the best place for this; Forum? New ticket here? You tell me and I'll meet you there.)

**Comment by adomasven** [comment]
> I think that the maintainers of the Word and LibreOffice plugins might like to have a look a what I've done with that. Any ideas? (Sorry, this isn't the best place for this; Forum? New ticket here? You tell me and I'll meet you there.)

@KarlHegbloom GitHub is a great place for us to triage issues and sometimes get feedback from the community, but we appreciate it if the conversation is kept on topic. As described in Zotero [support pages](https://www.zotero.org/support/dev/start), the correct place to talk about these things is on [zotero-dev mailing list](https://groups.google.com/group/zotero-dev).

**Comment by adomasven** [comment]
> I also find "Automatically abbreviate journal titles" a misnomer for the option. Whether or not the style abbreviates journal titles is determined by the style. Instead, the toggle determines where the abbreviations come from. How about:
>
>"Use automatically generated journal title abbreviations"
> (If checked, MEDLINE journal title abbreviations are used that are based on the full titles stored in the "Publication" field. If unchecked, the value of the "Journal Abbr" field is used instead.)

A suggestion in the [forums](https://forums.zotero.org/discussion/65347/feedback-abbreviate-journal-titles-checkbox-in-doc-prefs) is to go for:

> Use MEDLINE journal abbreviations
> (The "Journal abbr" field will be ignored)

Any reasons why it can't be this unambiguous?

**Comment by bwiernik** [comment]
That sounds perfect to me (also much less wordy)

**Comment by adam3smith** [comment]
I agree that Kyle's suggestion is perfect given the status quo of what the box does.
The only question is at what point we'll want to use other automated lists. I think as a medium term goal for Zotero (and/or CSL) we should support abbreviation lists for bluebook, SBL, OSCOLA, etc. -- but given that this will likely still take some time, I think switching this now and changing it again later if we manage to add more abbreviation lists is fine.

**Comment by bwiernik** [comment]
When we have multiple lists, switching to a dropdown box (with the Zotero field as one option) seems like a good choice.
