### ISSUE TITLE
Add style previews to document preferences pane

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#31]

**Comment by dstillman** [comment]
This would be a https://github.com/zotero/zotero issue.

**Comment by adomasven** [comment]
I know the actual code is under zotero/zotero, but logically it concerns word integration (and zotero/zotero is crowded with issues), so we may as well have it here.

**Comment by dstillman** [comment]
No, this should go where the code goes, because that's where we'll look for it. And it certainly doesn't make sense to put it in a platform-specific repo.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/issues/1195
