### ISSUE TITLE
{Bibliography} remains when switching to a style without bibliography

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#36]
Reproduction:

1. Choose APA
2. Insert a citation
3. Insert bibliography
4. Switch to a bibliographyless style, such as ISO-690

Result:
Bibliography is replaced with "{Bibliography}"

Expected result:
Bibliography is removed

Other errors:
When attempting to edit the bibliography in a bibliographyless style, when it's been previously inserted, an error is displayed:

```
Zotero experienced an error updating your document.

bib[0] is undefined
```

**Comment by dstillman** [comment]
Assuming this is a cross-platform issue, move to zotero/zotero.
