### ISSUE TITLE
Bibliography not displayed if no in-text citations.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#37]
The current behaviour we have is inconsistent with itself.

### Problem No. 1:

1. Create a fresh document
1. Insert a citation
1. Insert bibliography
1. Add more entries to bibliography via Edit Bibliography interface
1. Remove the citation
1. Refresh

**Result**:
In place of bibliography we display {Bibliography}. If you remove the {Bibliography} field and click "Insert Bibliography" again {Bibliography} is inserted again.

**Proposed change**:
Custom entries are displayed

---

### Problem No. 2

1. Create a fresh document
1. Attempt to insert bibliography

**Result**:
Error displayed informing you need to insert citations first

**Proposed change**:
{Bibliography} is inserted, which can then be edited to add custom entries

---

There have been [reports](https://forums.zotero.org/discussion/comment/272903/#Comment_272903) of this on the forums recently.

Comments welcome.

**Comment by dstillman** [comment]
Move to zotero/zotero.
