### ISSUE TITLE
Disable track changes when inserting citation and re-enable after.

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#43]
I believe there's code that should do it already, but there are [reports](https://forums.zotero.org/discussion/comment/296410/#Comment_296410) of it not working correctly

**Comment by daszlosek** [comment]
I just wanted to see if there was an update on this? It is still not working correctly.

**Comment by adomasven** [comment]
No updates for the immediate future.

**Comment by bilderbuchi** [comment]
@adomasven Could you confirm if that change also preserves the "Display for Review" setting? I am with Zotero 5.0.87 and re-installed the Word plugin today (After I saw the new release on Github), and using the "Simple markup" view. When I add a reference, I end up in the "All markup" view afterwards.

**Comment by bilderbuchi** [comment]
Oh, I just found out how to tell. It seems I am on Zotero Word for Windows Integration (5.0.14.SA.5.0.87, extension), so I guess the new release has not propagated to me, yet. I will try again later.

**Comment by dstillman** [comment]
@bilderbuchi: https://forums.zotero.org/discussion/comment/357697/#Comment_357697

**Comment by adomasven** [comment]
@bilderbuchi The behaviour you're seeing has always been like that. Zotero needs to disable review markup before reading the citations in the document and unfortunately the word API does not provide the option to choose between All markup and Simple markup. So if the plugin detects that markup display is enabled it will disable it temporarily and re-enable, possibly to the wrong type.

**Comment by bilderbuchi** [comment]
Thanks for the pointer to the beta! I wrongly assumed plugins are outside the main Zotero release cycle.
@adomasven Oh, shoot. So, I guess the [VB property/enum](https://docs.microsoft.com/en-us/office/vba/api/word.wdrevisionsmarkup) to this is not accessible to you, then. 
Thanks for explaining!

**Comment by adomasven** [comment]
@bilderbuchi Ah, it is available, I just didn't realize it existed. Thanks for pointing it out, we'll set this right too.

**Comment by bwiernik** [comment]
@adomasven Would it be possible to re-enable Track Changes when setting the display text for a citation? It would be nice to be able to that a citation was edited, but not worth it if it also leads to the Field Code tracking message.
