### ISSUE TITLE
Slow interaction with the plugin

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#46]
A [lot](https://forums.zotero.org/discussion/69957/slow-response-from-word-plugin) of [reports](https://forums.zotero.org/discussion/70111/speed-drop-in-window-pop-up-of-add-edit-citation-in-ms-word-2016) of this since we started signing the macros in the template. We could install the unsigned template for everyone and move the signed template under a preference as a workaround.

**Comment by dstillman** [comment]
Why do you think the signing is what's causing the slowdown?

Where's the actual slowdown in the debug output? Is it just before this?

> (3)(+0377958): Integration: Instantiating @zotero.org/Zotero/integration/application?agent=WinWord;1 for command addEditCitation with doc C:\Users\[…]\Google Drive\[…].docx

Is there anything else that happens in Zotero before this that we can add logging for?

**Comment by dstillman** [comment]
(If we're sure this started with the signed version, and there were no concurrent changes in the client, it seems more likely that it's something about the Word version I'm using to do the signing (which I assume rebuilds them) than the signing itself.)

**Comment by adomasven** [comment]
> Is there anything else that happens in Zotero before this that we can add logging for?

Not much.

> Where's the actual slowdown in the debug output? Is it just before this?

It wouldn't show up, since it seems that the macro in Word is taking a long time to run.

> Why do you think the signing is what's causing the slowdown?

People that install older debugging versions without signing of the extension that I have been asking to test them for some crashing issues report that the slowdown disappears.

> It seems more likely that it's something about the Word version I'm using to do the signing (which I assume rebuilds them) than the signing itself.

Could be, although I have built the latest .dotm files with Word 2016 and I assume that's what you used to sign.

I cannot reproduce the slowdown, so unless you have any ideas, I'm for just not installing the signed version, unless users change a pref.

**Comment by dstillman** [comment]
A pref would be really clumsy, and I don't think that's justified yet — aside from the fact that it would be a really strange bug, both of the reports linked above make the slowdown sound quite variable, so I don't think we can conclude much from brief testing with other versions. But I can build an unsigned version with the same version of Word and we can have people try that (and also switch back and confirm that the slowdown returns).

**Comment by adomasven** [comment]
Most of the talking about the slowdown was here https://forums.zotero.org/discussion/69009/zotero-upgrade-crashing-microsoft-word

> But I can build an unsigned version with the same version of Word and we can have people try that (and also switch back and confirm that the slowdown returns).

Sure, let's try it.

**Comment by adomasven** [comment]
No reports about this any longer
