### ISSUE TITLE
Option for toggling to Zotero codes and back

### ISSUE THREAD

**Issue by zuphilip** [zotero/zotero-word-for-windows-integration#5]
I would like to suggest an option in the coming new Zotero ribbon entry in Word #1 for toggling to the Zotero codes and back. The shortcut ALT+F9 is at least for me one of many shortcuts I cannot remember, because I don't use it that often. It could be subsumed also in the preferences as the deleting codes from document is at the moment planned, cf.
![Zotero Word Ribbon](https://cloud.githubusercontent.com/assets/7301964/2743371/074ca344-c713-11e3-81d9-facc354cb522.png)

**Comment by simonster** [comment]
I'm not totally sold on this. Ordinary users shouldn't ever have to look at the field codes, but might accidentally click a button in the ribbon and not realize what happened.

**Comment by dstillman** [comment]
Yeah, I don't think we want to do this. This is entirely a Word function.

**Comment by aurimasv** [comment]
>Ordinary users shouldn't ever have to look at the field codes, but might accidentally click a button in the ribbon and not realize what happened.

That's exactly the issue with Alt+F9 currently. Perhaps it would be possible for Zotero to recognized when field codes are toggled and inform the user how to toggle them back.

**Comment by zuphilip** [comment]
If the user click accidentally on a button and sees all this code stuff, and if that is clearly a toggle button, then it should be clear to just click the button again. Or let us say we just use a `<input type="checkbox">` or however this is named in Word. If the user clicks accidentally on the key combination then he might be stucked without any clue how to undo it. Proof that this happens: https://twitter.com/Duhem_/status/643812478414098432

**Comment by simonster** [comment]
A checkbox seems like it might be reasonable, but it's not clear how to keep the current state of the field codes setting and keep it up to date. The <a href="https://msdn.microsoft.com/en-us/library/office/dn320473.aspx">list of events</a> we could listen for doesn't seem to cover settings changes. If we want to do something, I think Aurimas probably has the right idea.

**Comment by bwiernik** [comment]
If Zotero wanted to add a toggle button (indicating the state) to show/hide field codes, that's as simple as adding in the built-in ribbon button to the Zotero tab. The relevant control id is idMso="FieldCodes" (for View Field Codes). A related potentially useful command that gets requested somewhat frequently on the forums is how to make the Zotero fields more visible. For that, we could add idMso="FieldShading" (for Show Field Shading).

**Comment by adomasven** [comment]
> The shortcut ALT+F9 is at least for me one of many shortcuts I cannot remember, because I don't use it that often.

That's exactly the point though. It is something that has very rare and specific use and shouldn't be exposed to end users. We don't even have information about this in the debugging broken documents kb page. Checking whether field codes are displayed and prompting the user on Zotero actions is probably a reasonable solution on our end in terms of reducing confusion when field code display gets accidentally toggled.

> A related potentially useful command that gets requested somewhat frequently on the forums is how to make the Zotero fields more visible. For that, we could add idMso="FieldShading" (for Show Field Shading).

This might be useful, but once again it's a Word function and will shade other things, such as ToC, figure references, tables, etc. We could maybe have a toggle in Doc Prefs after revisions in #30, where it clearly states that it will shade all Word fields.

**Comment by adomasven** [comment]
Should just be superseded by #26.
