### ISSUE TITLE
New Word Startup folder location

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#51]
We have had two reports of the Word startup location changing to `C:\Users\username\AppData\Local\Packages\Microsoft.Office.Desktop_8wekyb3d8bbwe\LocalCache\Roaming\Microsoft\Word\`, should investigate:

https://forums.zotero.org/discussion/comment/319645#Comment_319645
https://forums.zotero.org/discussion/comment/319976#Comment_319976

**Comment by dstillman** [comment]
It seems like `8wekyb3d8bbwe` is a constant, though. Can we check for the existence of that directory and write to it if it exists?

**Comment by dstillman** [comment]
Another report: https://forums.zotero.org/discussion/comment/322896/#Comment_322896

We should definitely try to copy to that folder if we can.

**Comment by adomasven** [comment]
Our code is looking up the startup using the "correct" Microsoft way, by looking it up in the [registry](https://github.com/zotero/zotero-word-for-windows-integration/blob/master/resource/installer.jsm#L88). There should be a better way to do this than hardcoding. I will try installing via the app store and see what's up.

**Comment by dstillman** [comment]
This is pretty critical, so unless we have an immediate fix for that uses the registry, we should use the hard-coded location for now, since it does seem to be consistent.

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero-word-for-windows-integration/commit/087aab0c658ff970f6c789e7123e760bed0cde78

I could get an install of Word to use the sandboxed location for the startup directory, probably because I have a bunch of older versions of Office in my VM that I am not removing to test this very likely without any success. Either way, I added the sandboxed location to the installer code and hopefully Zotero will have enough permissions to write there.
