### ISSUE TITLE
Cannot convert to an inline style if using endnotes

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#52]
https://forums.zotero.org/discussion/74564/unable-to-update-citation-style-in-document

**Comment by dstillman** [comment]
We still get reports of this periodically:

https://forums.zotero.org/search?Search=convertToNoteType

**Comment by dstillman** [comment]
If we can't fix this easily, we really need to show a clearer error message that explains what to do:

https://forums.zotero.org/search?Search=convertToNoteType

(Just got another via email.)
