### ISSUE TITLE
Preserve the "Display for Review" setting across citation reads/changes

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-word-for-windows-integration#56]
See https://github.com/zotero/zotero-word-for-windows-integration/issues/43#issuecomment-638853327 and onwards for discussion

The API is available at https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.revisionsfilter?view=word-pia

**Comment by bilderbuchi** [comment]
May I suggest a more precise title along the lines of 'Preserve the "Display for Review" setting across citation reads/changes', as some users are bound to use full markup, some none, some simple markup.

**Comment by bilderbuchi** [comment]
ha, what, fixed already? insane response time! 👏 ❤️

**Comment by adomasven** [comment]
Will be available in the <a href="https://www.zotero.org/support/dev_builds">Zotero Beta</a> within the next 24 hours and pushed out for the full release version sometime later assuming I didn't introduce any bugs

**Comment by dstillman** [comment]
Beta is out now.
