### ISSUE TITLE
Word plugin digital signature

### ISSUE THREAD

**Issue by pookiege** [zotero/zotero-word-for-windows-integration#58]
The signature for zotero.dotm will expire by the end of the year. Could you sign it again ?

**Comment by dstillman** [comment]
We've signed the template with a new certificate in the latest <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a>, and it's available for download [here](https://github.com/zotero/zotero-word-for-windows-integration/tree/master/install). The updated template will be included in 5.0.95 soon.
