### ISSUE TITLE
word 2019 "macro cannot be found or has been disabled"

### ISSUE THREAD

**Issue by xkxsxkx** [zotero/zotero-word-for-windows-integration#61]
when i use this plugin in word 2019,  pop up "The macro cannot be found or has been disabled because of your security settings"，

i try to "file-> word option -> Trust Center" enable all macro 

but it still can't work，The tag is an empty block, not "zotero"

**Comment by adomasven** [comment]
Please post bug reports on the [Zotero forum](https://forums.zotero.org/). This tracker is for developer use only.
