### ISSUE TITLE
Citation in image captions

### ISSUE THREAD

**Issue by Alainx277** [zotero/zotero-word-for-windows-integration#64]
It is not possible to insert a citation into an image caption by using the Zotero dialog. However, it can be done manually by copying an existing citation into the caption, but it won't be updated.

Is there a technical limitation making citations in image captions impossible?

**Comment by adomasven** [comment]
Yes there is a technical limitation and citing will likely break if you insert citations into captions. Also, all Zotero support is done on the Zotero Forums, please do not open issues on our repos.
