### ISSUE TITLE
GetActiveDocument will cause `TypeError: documentName is null`;

### ISSUE THREAD

**Issue by cesaryuan** [zotero/zotero-word-for-windows-integration#66]
getActiveDocument will cause `TypeError: documentName is null`;

It's a simple bug, please fix it. Thanks!

https://github.com/zotero/zotero-word-for-windows-integration/blob/c8a640788e53cdfa46e9721792b2b31e4369e6b0/components/zoteroWinWordIntegration.js#L239-L253

**Comment by adomasven** [comment]
This function is never used in the current code-paths of Zotero and this has likely been broken for years. How are you using this code that it's affecting you?

**Comment by cesaryuan** [comment]
> This function is never used in the current code-paths of Zotero and this has likely been broken for years. How are you using this code that it's affecting you?

Thanks for your reply! I'm making a plugin to simplify the process of adding citations to Word. In this situation, I'd like to run the following code:
```
Zotero.Integration.execCommand("WinWord", 'addEditCitation', null)
```
In the above code, `execCommand`'s third argument is assigned by null because I see the logic in the Zotero repo:

https://github.com/zotero/zotero/blob/d866a10a2b56e96631a1563572d3f2918f1f006a/chrome/content/zotero/xpcom/integration.js#L246

which means if I pass null to the third argument, I'll be able to make this command to run at the active document.

**Comment by adomasven** [comment]
Right. Did you actually test your PR codefix and behavior? Since this code-path hasn't been used for 10 years it may not work at all.

**Comment by cesaryuan** [comment]
> Right. Did you actually test your PR codefix and behavior? Since this code-path hasn't been used for 10 years it may not work at all.

Sure, I have test it locally by modified the `.\Zotero\extensions\zoteroWinWordIntegration@zotero.org\components\zoteroWinWordIntegration.js` locally.

It works.
