### ISSUE TITLE
Office 2016 support

### ISSUE THREAD

**Issue by tholden** [zotero/zotero-word-for-windows-integration#8]
Running Word 2016 produces an error message that "the add in template is not valid" for Zotero.dot.
Fixing this would be greatly appreciated.

**Comment by marckl67** [comment]
You can try this update of zotero.dot for Office 2007 and above. This addon adds Zotero function in the "Reference" ribbon of Word.

Download zotero.dotm here. 
https://github.com/marckl67/zotero-word-for-windows-integration/blob/master/install/Zotero.dotm?raw=true

Then copy the file in Word STARTUP directory
C:\Users\<user>\AppData\Roaming\Microsoft\Word\STARTUP

Remove the zotero.dot file from this directory

You can have more information here
https://github.com/zotero/zotero-word-for-windows-integration/issues/1

**Comment by tholden** [comment]
Wonderful. That seems to work.

**Comment by sapindus** [comment]
I replace the zotero.dot with zotero.dotm ,the icons dose appear in the ribbon.but when I click one of the button ,it says"zotero integration error: zotero can not load the component necessary for communicating word pocessing software".How can i solve this problem

**Comment by marckl67** [comment]
Did you have a look here
https://www.zotero.org/support/word_processor_plugin_troubleshooting Word 2010: "Could not find a running Word instance"
or here
https://forums.zotero.org/discussion/23605/zotero-could-not-load-the-component-required-with-word-for-windows/
